  version: '3'

  services:
    web:
      build: .
      container_name: flask-gunicorn-voice-extractor
      restart: on-failure
      ports:
        - "${PORT}:${PORT}"
    nginx:
      image: nginx:1.17
      container_name: ngx-flask-voice-extractor
      ports:
        - "81:81"
      volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./app/static/:/static/
      depends_on:
        - web
